# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code..
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  InjectAlmOctaneTasks: 'true'
  OctaneServiceConnection: 'qa9'
  WorkspaceList: '1002'
  ALMOctaneLogLevel: 'debug'
  system.debug: 'true'
  system.debugContext: 'true'
  GithubRepositoryConnection: 'git'


jobs:
- job: AlmOctanePipelineStart
  condition: always()
  steps:
  - task: octane-start-task@1
    inputs:
      OctaneServiceConnection: $(OctaneServiceConnection)
      WorkspaceList: $(WorkspaceList)
      GithubRepositoryConnection: $(GithubRepositoryConnection)


- job: A
  steps:
  - script: echo Hello, Job A!
    displayName: 'Run a one-line script'
  - task: octane-connection-verifier@1
    inputs:
      OctaneServiceConnection: $(OctaneServiceConnection)
  dependsOn:
  - AlmOctanePipelineStart

- job: B
  dependsOn: AlmOctanePipelineStart
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: AlmOctanePipelineEnd
  condition: always()
  steps:
  - task: octane-end-task@1
    inputs:
      OctaneServiceConnection: $(OctaneServiceConnection)
      WorkspaceList: $(WorkspaceList)
      GithubRepositoryConnection: $(GithubRepositoryConnection)
  dependsOn:
  - AlmOctanePipelineStart
  - A
  - B
